### ISSUE TITLE
"Cannot add or update a child row: a foreign key constraint fails " for ohrm_user_role_data_group

### ISSUE THREAD

**Issue by yashiscool123** [orangehrm/orangehrm#1780]
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source: 5.5
- Platform: Windows
- PHP version:  8.2.12
- Database and version: MySQL 10.4.32
- Web server: XAMPP (Apache)
- Browser: Chrome 
Instance details: {"os":{"os":"Windows NT","release_name":"10.0","version_info":"build 22621 (Windows 11)"},"php":{"version":"8.2.12"},"mysql":{"client_version":"mysqlnd 8.2.12","server_version":"10.4.32-MariaDB","conn_type":"127.0.0.1 via TCP\/IP"},"server":"Apache\/2.4.58 (Win64) OpenSSL\/3.1.3 PHP\/8.2.12","ohrm":{"version":"5.5"}}

### Describe the bug

When doing a clean first time installation facing the following issue:

Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ohrm`.`ohrm_user_role_data_group`, CONSTRAINT `ohrm_user_role_data_group_ibfk_1` FOREIGN KEY (`user_role_id`) REFERENCES `ohrm_user_role` (`id`) ON DELETE CASCADE)
[installer.log](https://github.com/orangehrm/orangehrm/files/13751469/installer.log)

### To reproduce

Do a simple first time installation of XAMPP and then deploy the OHRM in the HTDOCS folder and run the installation as usual in a Windows 11 environment.

**Comment by devishke-orange** [comment]
Hi @yashiscool123,

This is a known issue. Please see https://github.com/orangehrm/orangehrm/issues/1779#issuecomment-1858775378

**Comment by devishke-orange** [comment]
Hi @yashiscool123,

This issue is fixed in OrangeHRM 5.6: https://github.com/orangehrm/orangehrm/releases/tag/v5.6

**Comment by yshah-fluree** [comment]
I can still see this issue persisting. Please find the attached log.
[installer.log](https://github.com/orangehrm/orangehrm/files/14406650/installer.log)

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ohrm`.`ohrm_user_role_data_group`, CONSTRAINT `ohrm_user_role_data_group_ibfk_1` FOREIGN KEY (`user_role_id`) REFERENCES `ohrm_user_role` (`id`) ON DELETE CASCADE) [] []

**Comment by devishke-orange** [comment]
Hi @yashiscool123 , @yshah-fluree 

We have identified the cause of this issue. As it turns out, it's due to the timeout defined by XAMPP. Please follow the steps below and let me know if you can install the system.

1. Open XAMPP and make sure the Apache server is stopped. (Screenshot for reference)
![Screenshot 2024-03-07 074022](https://github.com/orangehrm/orangehrm/assets/97493184/3871dad8-0502-4b20-ba87-6b0d053f096b)

2. In the row of buttons corresponding to Apache, click on "Config".
![Screenshot 2024-03-07 074135](https://github.com/orangehrm/orangehrm/assets/97493184/c27899bf-0d81-4200-9b78-adbda6deb37b)

3. Select "PHP (php.ini)"
![Screenshot 2024-03-07 074249](https://github.com/orangehrm/orangehrm/assets/97493184/3fa88d0b-2a02-4273-a473-fbbe142fdf56)

4. This will open up Notepad. Click on Notepad and search for a line with the text "max_execution_time"
![Screenshot 2024-03-07 074525](https://github.com/orangehrm/orangehrm/assets/97493184/df6ec4cc-c90d-4c4a-9e66-2c6e797ed006)

5. It should be equal to 120 by default. Increase the number to a higher value. Make sure to save the file.
![Screenshot 2024-03-07 074652](https://github.com/orangehrm/orangehrm/assets/97493184/33fa5278-791a-4e1f-8826-13da863753a2)

6. Now, restart the Apache server (and MySQL if it's not already started) and try installing OrangeHRM. If it still doesn't work, try increasing the timeout to a higher value.

**Comment by yshah-fluree** [comment]
Thank

> Hi @yashiscool123 , @yshah-fluree
> 
> We have identified the cause of this issue. As it turns out, it's due to the timeout defined by XAMPP. Please follow the steps below and let me know if you can install the system.
> 
> 1. Open XAMPP and make sure the Apache server is stopped. (Screenshot for reference)
>    ![Screenshot 2024-03-07 074022](https://private-user-images.githubusercontent.com/97493184/310724914-3871dad8-0502-4b20-ba87-6b0d053f096b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTQwNjQsIm5iZiI6MTcwOTc5Mzc2NCwicGF0aCI6Ii85NzQ5MzE4NC8zMTA3MjQ5MTQtMzg3MWRhZDgtMDUwMi00YjIwLWJhODctNmIwZDA1M2YwOTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZDNmNTliNDZmYWI4MWJlMTg4OGQ0MTJiOTg0MDQ0ZjY4M2MzNjIwOTY5Njk3YjMzMjMyOGRjNDFkYmFkNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Et2UYHD-RBhpFdcb6OUGg8yG29eGFpos643fK4_JpA)
> 2. In the row of buttons corresponding to Apache, click on "Config".
>    ![Screenshot 2024-03-07 074135](https://private-user-images.githubusercontent.com/97493184/310724953-c27899bf-0d81-4200-9b78-adbda6deb37b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTQwNjQsIm5iZiI6MTcwOTc5Mzc2NCwicGF0aCI6Ii85NzQ5MzE4NC8zMTA3MjQ5NTMtYzI3ODk5YmYtMGQ4MS00MjAwLTliNzgtYWRiZGE2ZGViMzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZDc5NjE4OGIwNmZkNDg1NzIzNWUwY2IwMjgzYTNhODBmMWZhODFlZDYyMWIzOTAyYmJlNzc0MzNmNjYzNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j8QuAEmY3K7naI3ZHPU-d7wK5MpxqDZlusz9pm2WDqk)
> 3. Select "PHP (php.ini)"
>    ![Screenshot 2024-03-07 074249](https://private-user-images.githubusercontent.com/97493184/310724992-3fa88d0b-2a02-4273-a473-fbbe142fdf56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTQwNjQsIm5iZiI6MTcwOTc5Mzc2NCwicGF0aCI6Ii85NzQ5MzE4NC8zMTA3MjQ5OTItM2ZhODhkMGItMmEwMi00MjczLWE0NzMtZmJiZTE0MmZkZjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NTE2M2ZmNDk4YmU4Y2RhM2UxM2Q1OWUyMzg2YmM0ZDIyMTQ0MWY1MWY5OGZhMDA1ZmIwYWIzNGFmMjI4YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ljhiGpt9cBjCs61WUKZQwz_uFnWNq99wxP7rp-MzVUo)
> 4. This will open up Notepad. Click on Notepad and search for a line with the text "max_execution_time"
>    ![Screenshot 2024-03-07 074525](https://private-user-images.githubusercontent.com/97493184/310725039-df6ec4cc-c90d-4c4a-9e66-2c6e797ed006.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTQwNjQsIm5iZiI6MTcwOTc5Mzc2NCwicGF0aCI6Ii85NzQ5MzE4NC8zMTA3MjUwMzktZGY2ZWM0Y2MtYzkwZC00YzRhLTllNjYtMmM2ZTc5N2VkMDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0Zjk0ZWM4YTQ4Njk4Zjc3ODg4M2I2YWRjYzZmOTIwMGQxNDJkOTA4YTdmMDdmZWEzOGY2YmRhOTc0NGMxNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eqe3xabWVQnMU-PGGKO7sksBbFTFYSpeDOPJOKoBspE)
> 5. It should be equal to 120 by default. Increase the number to a higher value. Make sure to save the file.
>    ![Screenshot 2024-03-07 074652](https://private-user-images.githubusercontent.com/97493184/310725076-33fa5278-791a-4e1f-8826-13da863753a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTQwNjQsIm5iZiI6MTcwOTc5Mzc2NCwicGF0aCI6Ii85NzQ5MzE4NC8zMTA3MjUwNzYtMzNmYTUyNzgtNzkxYS00ZTFmLTg4MjYtMTNkYTg2Mzc1M2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTBjOGUyYjBjNTJjOGY2YTVmY2FmYWQ1M2QyZmM1NWY2MTJjNDIxZDkzZTM1ZjE5NjkxN2NjNjlkMmYwOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UCUqjrQ9JHMbC6cs5oF8XkEHOaGfZWkk2fVJGdcebgo)
> 6. Now, restart the Apache server (and MySQL if it's not already started) and try installing OrangeHRM. If it still doesn't work, try increasing the timeout to a higher value.



Thank you.. Increasing the "max_execution_time" value to 240 helped in a successful installation.

**Comment by devishke-orange** [comment]
I'm closing this since the issue was resolved.
