### ISSUE TITLE
Google OpenId Provider not working in 4.1

### ISSUE THREAD

**Issue by danielbair** [orangehrm/orangehrm#222]
I had configured and working a google openID provider in OrangeHRM OS 3.3.3 but after upgrading to 4.1 it does not work anymore. I've checked the configuration between OrangeHRM and Google and I can't see why it wouldn't work.

v3.3.3 Google openID provider in OrangeHRM working.
v4.1 Google openID provider in OrangeHRM NOT working.

**Comment by kavithagurusamy** [comment]
@danielbair The fix will be available in our next release for the community, this is planned for next week.

**Comment by kavithagurusamy** [comment]
This is fixed in 4.1.1

**Comment by kavithagurusamy** [comment]
This is fixed in 4.3.1

Refer the latest SourceForge release 
https://sourceforge.net/projects/orangehrm/files/stable/4.3.1/

**Comment by danielbair** [comment]
This issue is back again... OrangeHRM OS 5.7 was configured and working, but now Google says "Error 400: redirect_uri_mismatch" and in the details it says:

> 
You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.
If you're the app developer, register the redirect URI in the Google Cloud Console.
Request details: redirect_uri=https://mydomain.org/orangeHRM/web/index.php/openidauth/openIdCredentials flowName=GeneralOAuthFlow


And then when I attempt to put that URI in the [Google Cloud Client Config](https://console.cloud.google.com/auth/clients) it gives an error and says "white space not allowed in the URI"

**Comment by RajithaKumara** [comment]
Hi @danielbair ,
Could you please try again changing Google cloud Rediect URI.
In your case Redirect URI is correct: `https://<your-domain>.org/orangeHRM/web/index.php/openidauth/openIdCredentials`

Here are new help guides for 5.7 version;
https://starterhelp.orangehrm.com/hc/en-us/articles/12392313182236--Set-up-Social-Media-Authentication
https://starterhelp.orangehrm.com/hc/en-us/articles/12392345874076-Set-up-Authentication-Providers

**Comment by danielbair** [comment]
Thank you. I already had that, but what I didn't notice was that both www.mydomain.org and mydomain.org were valid for my OrangeHRM instance. I added both in the Google Cloud Client Config and now its working correctly.
