### ISSUE TITLE
Feature request for OpenID Connect or oauth 2.0

### ISSUE THREAD

**Issue by yonib05** [orangehrm/orangehrm#472]
Google as well as many other providers are shutting down there support for OpenID 2.0 in favor of OpenID Connect and Oauth 2.0.

It would be awesome if Orangehrm supported this in place of or in addition to the OpenID 2.0 in supports out of the box.

**Comment by kavithagurusamy** [comment]
Thanks @yonib05 for the update.

We are working on the fix, It will be available on our next release.

**Comment by yonib05** [comment]
That's great to hear looking forward to it!

**Comment by kavithagurusamy** [comment]
This is fixed in 4.3.1
Download the latest release from sourceforge 
https://sourceforge.net/projects/orangehrm/files/stable/4.3.1/

**Comment by Mrs-Feathers** [comment]
i'm in version 4.9 and i'm still seeing the openid 2 and google. there is no support for openid connect here

**Comment by Mrs-Feathers** [comment]
nevermind, updated to 5.5 and its all disabled with a "comming soon" screen
